
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVE_H
#define TESTSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 ObjDict_valueRangeTest (UNS8 typeValue, void * value);
const indextable * ObjDict_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data ObjDict_Data;
extern INTEGER32 step_pos;		/* Mapped at index 0x2001, subindex 0x00*/
extern INTEGER32 step_speed;		/* Mapped at index 0x2002, subindex 0x00*/

#endif // TESTSLAVE_H
