
/* File generated by gen_cfile.py. Should not be modified. */

#include "PD4Master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 PD4_Controlword[4] = {0x0, 0x0, 0x0, 0x0};    /* Mapped at index 0x2011, subindex 0x00 */
UNS16 PD4_Status[4] = {0x0, 0x0, 0x0, 0x0};   /* Mapped at index 0x2012, subindex 0x00 */
UNS32 PD4_SubMode[4] = {0x1, 0x1, 0x41, 0x1};    /* Mapped at index 0x2013, subindex 0x00 */
INTEGER8 PD4_Mode[4] = {0x1, 0x6, 0x1, 0x1};    /* Mapped at index 0x2014, subindex 0x00 */
INTEGER32 PD4_Position[4] = {0x0, 0x0, 0x0, 0x0};   /* Mapped at index 0x2015, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestMaster_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestMaster_iam_a_slave = 0;

TIMER_HANDLE TestMaster_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestMaster_obj1000 = 0x12D;	/* 301 */
                    subindex TestMaster_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestMaster_obj1001 = 0x0;	/* 0 */
                    subindex TestMaster_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestMaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t TestMaster_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 TestMaster_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t TestMaster_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 TestMaster_obj1006 = 0xC350;	/* 50000 */
                    ODCallback_t TestMaster_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 TestMaster_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestMaster_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 TestMaster_obj1014 = 0x80;	/* 128 */
                    subindex TestMaster_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 TestMaster_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 TestMaster_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 TestMaster_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex TestMaster_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 TestMaster_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex TestMaster_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 TestMaster_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 TestMaster_obj1281_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex TestMaster_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 TestMaster_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 TestMaster_obj1282_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex TestMaster_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1282 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1282_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1282_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1282_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1540 */
                    UNS32 TestMaster_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x584;	/* 1412 */
                    UNS8 TestMaster_obj1283_Node_ID_of_the_SDO_Server = 0x4;	/* 4 */
                    subindex TestMaster_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1283 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1283_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1283_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1283_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1400_COB_ID_used_by_PDO = 0x80000181;	/* 2147484033 */
                    UNS8 TestMaster_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex TestMaster_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Event_Timer }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1401_COB_ID_used_by_PDO = 0x80000182;	/* 2147484034 */
                    UNS8 TestMaster_obj1401_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1402_COB_ID_used_by_PDO = 0x80000183;	/* 2147484035 */
                    UNS8 TestMaster_obj1402_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1403_COB_ID_used_by_PDO = 0x80000184;	/* 2147484036 */
                    UNS8 TestMaster_obj1403_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1600[] = 
                    {
                      0x20120010,	/* 538050576 */
                      0x20150020	/* 538247200 */
                    };
                    subindex TestMaster_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[1] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1601[] = 
                    {
                      0x20220010,	/* 539099152 */
                      0x20250020	/* 539295776 */
                    };
                    subindex TestMaster_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[1] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1602 = 2; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1602[] = 
                    {
                      0x20320010,	/* 540147728 */
                      0x20350020	/* 540344352 */
                    };
                    subindex TestMaster_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[1] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1603 = 2; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1603[] = 
                    {
                      0x20420010,	/* 541196304 */
                      0x20450020	/* 541392928 */
                    };
                    subindex TestMaster_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[1] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1800_COB_ID_used_by_PDO = 0x80000201;	/* 2147484161 */
                    UNS8 TestMaster_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1801_COB_ID_used_by_PDO = 0x80000202;	/* 2147484162 */
                    UNS8 TestMaster_obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1802_COB_ID_used_by_PDO = 0x80000203;	/* 2147484163 */
                    UNS8 TestMaster_obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1803_COB_ID_used_by_PDO = 0x80000204;	/* 2147484164 */
                    UNS8 TestMaster_obj1803_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A00 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A00[] = 
                    {
                      0x20110010,	/* 537985040 */
                      0x20140008,	/* 538181640 */
                      0x20130020	/* 538116128 */
                    };
                    subindex TestMaster_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[2] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A01 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A01[] = 
                    {
                      0x20210010,	/* 539033616 */
                      0x20240008,	/* 539230216 */
                      0x20230020	/* 539164704 */
                    };
                    subindex TestMaster_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[2] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A02 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A02[] = 
                    {
                      0x20310010,	/* 540082192 */
                      0x20340008,	/* 540278792 */
                      0x20330020	/* 540213280 */
                    };
                    subindex TestMaster_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[2] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A03 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A03[] = 
                    {
                      0x20410010,	/* 541130768 */
                      0x20440008,	/* 541327368 */
                      0x20430020	/* 541261856 */
                    };
                    subindex TestMaster_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[2] }
                     };

/* index 0x1F22 :   Concise DCF. */
                    UNS8 TestMaster_highestSubIndex_obj1F22 = 2; /* number of subindex - 1*/
                    UNS8* TestMaster_obj1F22[] = 
                    {
                      (UNS8*)"",
                      (UNS8*)"\x01\x00\x00\x00\x17\x10\x00\x02\x00\x00\x00\xe8\x03"
                    };
                    subindex TestMaster_Index1F22[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1F22 },
                       { RW, domain, 0, (void*)&TestMaster_obj1F22[0] },
                       { RW, domain, 13, (void*)&TestMaster_obj1F22[1] }
                     };

/* index 0x2011 :   Mapped variable PD4_Controlword_1 */
                    subindex TestMaster_Index2011[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PD4_Controlword[0] }
                     };

/* index 0x2012 :   Mapped variable PD4_Status_1 */
                    subindex TestMaster_Index2012[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PD4_Status[0] }
                     };

/* index 0x2013 :   Mapped variable PD4_SubMode_1 */
                    subindex TestMaster_Index2013[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&PD4_SubMode[0] }
                     };

/* index 0x2014 :   Mapped variable PD4_Mode_1 */
                    subindex TestMaster_Index2014[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&PD4_Mode[0] }
                     };

/* index 0x2015 :   Mapped variable PD4_Position_1 */
                    subindex TestMaster_Index2015[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&PD4_Position[0] }
                     };

/* index 0x2021 :   Mapped variable PD4_Controlword_2 */
                    subindex TestMaster_Index2021[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PD4_Controlword[1] }
                     };

/* index 0x2022 :   Mapped variable PD4_Status_2 */
                    subindex TestMaster_Index2022[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PD4_Status[1] }
                     };

/* index 0x2023 :   Mapped variable PD4_SubMode_2 */
                    subindex TestMaster_Index2023[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&PD4_SubMode[1] }
                     };

/* index 0x2024 :   Mapped variable PD4_Mode_2 */
                    subindex TestMaster_Index2024[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&PD4_Mode[1] }
                     };

/* index 0x2025 :   Mapped variable PD4_Position_2 */
                    subindex TestMaster_Index2025[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&PD4_Position[1] }
                     };

/* index 0x2031 :   Mapped variable PD4_Controlword_3 */
                    subindex TestMaster_Index2031[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PD4_Controlword[2] }
                     };

/* index 0x2032 :   Mapped variable PD4_Status_3 */
                    subindex TestMaster_Index2032[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PD4_Status[2] }
                     };

/* index 0x2033 :   Mapped variable PD4_SubMode_3 */
                    subindex TestMaster_Index2033[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&PD4_SubMode[2] }
                     };

/* index 0x2034 :   Mapped variable PD4_Mode_3 */
                    subindex TestMaster_Index2034[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&PD4_Mode[2] }
                     };

/* index 0x2035 :   Mapped variable PD4_Postion_3 */
                    subindex TestMaster_Index2035[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&PD4_Position[2] }
                     };

/* index 0x2041 :   Mapped variable PD4_Controlword_4 */
                    subindex TestMaster_Index2041[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PD4_Controlword[3] }
                     };

/* index 0x2042 :   Mapped variable PD4_Status_4 */
                    subindex TestMaster_Index2042[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PD4_Status[3] }
                     };

/* index 0x2043 :   Mapped variable PD4_SubMode_4 */
                    subindex TestMaster_Index2043[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&PD4_SubMode[3] }
                     };

/* index 0x2044 :   Mapped variable PD4_Mode_4 */
                    subindex TestMaster_Index2044[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&PD4_Mode[3] }
                     };

/* index 0x2045 :   Mapped variable PD4_Position_4 */
                    subindex TestMaster_Index2045[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&PD4_Position[3] }
                     };
/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestMaster_objdict[] = 
{
  { (subindex*)TestMaster_Index1000,sizeof(TestMaster_Index1000)/sizeof(TestMaster_Index1000[0]), 0x1000},
  { (subindex*)TestMaster_Index1001,sizeof(TestMaster_Index1001)/sizeof(TestMaster_Index1001[0]), 0x1001},
  { (subindex*)TestMaster_Index1005,sizeof(TestMaster_Index1005)/sizeof(TestMaster_Index1005[0]), 0x1005},
  { (subindex*)TestMaster_Index1006,sizeof(TestMaster_Index1006)/sizeof(TestMaster_Index1006[0]), 0x1006},
  { (subindex*)TestMaster_Index1014,sizeof(TestMaster_Index1014)/sizeof(TestMaster_Index1014[0]), 0x1014},
  { (subindex*)TestMaster_Index1016,sizeof(TestMaster_Index1016)/sizeof(TestMaster_Index1016[0]), 0x1016},
  { (subindex*)TestMaster_Index1018,sizeof(TestMaster_Index1018)/sizeof(TestMaster_Index1018[0]), 0x1018},
  { (subindex*)TestMaster_Index1280,sizeof(TestMaster_Index1280)/sizeof(TestMaster_Index1280[0]), 0x1280},
  { (subindex*)TestMaster_Index1281,sizeof(TestMaster_Index1281)/sizeof(TestMaster_Index1281[0]), 0x1281},
  { (subindex*)TestMaster_Index1282,sizeof(TestMaster_Index1282)/sizeof(TestMaster_Index1282[0]), 0x1282},
  { (subindex*)TestMaster_Index1283,sizeof(TestMaster_Index1283)/sizeof(TestMaster_Index1283[0]), 0x1283},
  { (subindex*)TestMaster_Index1400,sizeof(TestMaster_Index1400)/sizeof(TestMaster_Index1400[0]), 0x1400},
  { (subindex*)TestMaster_Index1401,sizeof(TestMaster_Index1401)/sizeof(TestMaster_Index1401[0]), 0x1401},
  { (subindex*)TestMaster_Index1402,sizeof(TestMaster_Index1402)/sizeof(TestMaster_Index1402[0]), 0x1402},
  { (subindex*)TestMaster_Index1403,sizeof(TestMaster_Index1403)/sizeof(TestMaster_Index1403[0]), 0x1403},
  { (subindex*)TestMaster_Index1600,sizeof(TestMaster_Index1600)/sizeof(TestMaster_Index1600[0]), 0x1600},
  { (subindex*)TestMaster_Index1601,sizeof(TestMaster_Index1601)/sizeof(TestMaster_Index1601[0]), 0x1601},
  { (subindex*)TestMaster_Index1602,sizeof(TestMaster_Index1602)/sizeof(TestMaster_Index1602[0]), 0x1602},
  { (subindex*)TestMaster_Index1603,sizeof(TestMaster_Index1603)/sizeof(TestMaster_Index1603[0]), 0x1603},
  { (subindex*)TestMaster_Index1800,sizeof(TestMaster_Index1800)/sizeof(TestMaster_Index1800[0]), 0x1800},
  { (subindex*)TestMaster_Index1801,sizeof(TestMaster_Index1801)/sizeof(TestMaster_Index1801[0]), 0x1801},
  { (subindex*)TestMaster_Index1802,sizeof(TestMaster_Index1802)/sizeof(TestMaster_Index1802[0]), 0x1802},
  { (subindex*)TestMaster_Index1803,sizeof(TestMaster_Index1803)/sizeof(TestMaster_Index1803[0]), 0x1803},
  { (subindex*)TestMaster_Index1A00,sizeof(TestMaster_Index1A00)/sizeof(TestMaster_Index1A00[0]), 0x1A00},
  { (subindex*)TestMaster_Index1A01,sizeof(TestMaster_Index1A01)/sizeof(TestMaster_Index1A01[0]), 0x1A01},
  { (subindex*)TestMaster_Index1A02,sizeof(TestMaster_Index1A02)/sizeof(TestMaster_Index1A02[0]), 0x1A02},
  { (subindex*)TestMaster_Index1A03,sizeof(TestMaster_Index1A03)/sizeof(TestMaster_Index1A03[0]), 0x1A03},
  { (subindex*)TestMaster_Index1F22,sizeof(TestMaster_Index1F22)/sizeof(TestMaster_Index1F22[0]), 0x1F22},
  { (subindex*)TestMaster_Index2011,sizeof(TestMaster_Index2011)/sizeof(TestMaster_Index2011[0]), 0x2011},
  { (subindex*)TestMaster_Index2012,sizeof(TestMaster_Index2012)/sizeof(TestMaster_Index2012[0]), 0x2012},
  { (subindex*)TestMaster_Index2013,sizeof(TestMaster_Index2013)/sizeof(TestMaster_Index2013[0]), 0x2013},
  { (subindex*)TestMaster_Index2014,sizeof(TestMaster_Index2014)/sizeof(TestMaster_Index2014[0]), 0x2014},
  { (subindex*)TestMaster_Index2015,sizeof(TestMaster_Index2015)/sizeof(TestMaster_Index2015[0]), 0x2015},
  { (subindex*)TestMaster_Index2021,sizeof(TestMaster_Index2021)/sizeof(TestMaster_Index2021[0]), 0x2021},
  { (subindex*)TestMaster_Index2022,sizeof(TestMaster_Index2022)/sizeof(TestMaster_Index2022[0]), 0x2022},
  { (subindex*)TestMaster_Index2023,sizeof(TestMaster_Index2023)/sizeof(TestMaster_Index2023[0]), 0x2023},
  { (subindex*)TestMaster_Index2024,sizeof(TestMaster_Index2024)/sizeof(TestMaster_Index2024[0]), 0x2024},
  { (subindex*)TestMaster_Index2025,sizeof(TestMaster_Index2025)/sizeof(TestMaster_Index2025[0]), 0x2025},
  { (subindex*)TestMaster_Index2031,sizeof(TestMaster_Index2031)/sizeof(TestMaster_Index2031[0]), 0x2031},
  { (subindex*)TestMaster_Index2032,sizeof(TestMaster_Index2032)/sizeof(TestMaster_Index2032[0]), 0x2032},
  { (subindex*)TestMaster_Index2033,sizeof(TestMaster_Index2033)/sizeof(TestMaster_Index2033[0]), 0x2033},
  { (subindex*)TestMaster_Index2034,sizeof(TestMaster_Index2034)/sizeof(TestMaster_Index2034[0]), 0x2034},
  { (subindex*)TestMaster_Index2035,sizeof(TestMaster_Index2035)/sizeof(TestMaster_Index2035[0]), 0x2035},
  { (subindex*)TestMaster_Index2041,sizeof(TestMaster_Index2041)/sizeof(TestMaster_Index2041[0]), 0x2041},
  { (subindex*)TestMaster_Index2042,sizeof(TestMaster_Index2042)/sizeof(TestMaster_Index2042[0]), 0x2042},
  { (subindex*)TestMaster_Index2043,sizeof(TestMaster_Index2043)/sizeof(TestMaster_Index2043[0]), 0x2043},
  { (subindex*)TestMaster_Index2044,sizeof(TestMaster_Index2044)/sizeof(TestMaster_Index2044[0]), 0x2044},
  { (subindex*)TestMaster_Index2045,sizeof(TestMaster_Index2045)/sizeof(TestMaster_Index2045[0]), 0x2045},
};

const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = TestMaster_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = TestMaster_Index1006_callbacks; break;
		case 0x1014: i = 4;break;
		case 0x1016: i = 5;break;
		case 0x1018: i = 6;break;
		case 0x1280: i = 7;break;
		case 0x1281: i = 8;break;
		case 0x1282: i = 9;break;
		case 0x1283: i = 10;break;
		case 0x1400: i = 11;break;
		case 0x1401: i = 12;break;
		case 0x1402: i = 13;break;
		case 0x1403: i = 14;break;
		case 0x1600: i = 15;break;
		case 0x1601: i = 16;break;
		case 0x1602: i = 17;break;
		case 0x1603: i = 18;break;
		case 0x1800: i = 19;*callbacks = TestMaster_Index1800_callbacks; break;
		case 0x1801: i = 20;*callbacks = TestMaster_Index1801_callbacks; break;
		case 0x1802: i = 21;*callbacks = TestMaster_Index1802_callbacks; break;
		case 0x1803: i = 22;*callbacks = TestMaster_Index1803_callbacks; break;
		case 0x1A00: i = 23;break;
		case 0x1A01: i = 24;break;
		case 0x1A02: i = 25;break;
		case 0x1A03: i = 26;break;
		case 0x1F22: i = 27;break;
		case 0x2011: i = 28;break;
		case 0x2012: i = 29;break;
		case 0x2013: i = 30;break;
		case 0x2014: i = 31;break;
		case 0x2015: i = 32;break;
		case 0x2021: i = 33;break;
		case 0x2022: i = 34;break;
		case 0x2023: i = 35;break;
		case 0x2024: i = 36;break;
		case 0x2025: i = 37;break;
		case 0x2031: i = 38;break;
		case 0x2032: i = 39;break;
		case 0x2033: i = 40;break;
		case 0x2034: i = 41;break;
		case 0x2035: i = 42;break;
		case 0x2041: i = 43;break;
		case 0x2042: i = 44;break;
		case 0x2043: i = 45;break;
		case 0x2044: i = 46;break;
		case 0x2045: i = 47;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestMaster_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestMaster_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index TestMaster_firstIndex = {
  0, /* SDO_SVR */
  7, /* SDO_CLT */
  11, /* PDO_RCV */
  15, /* PDO_RCV_MAP */
  19, /* PDO_TRS */
  23 /* PDO_TRS_MAP */
};

const quick_index TestMaster_lastIndex = {
  0, /* SDO_SVR */
  10, /* SDO_CLT */
  14, /* PDO_RCV */
  18, /* PDO_RCV_MAP */
  22, /* PDO_TRS */
  26 /* PDO_TRS_MAP */
};

const UNS16 TestMaster_ObjdictSize = sizeof(TestMaster_objdict)/sizeof(TestMaster_objdict[0]); 

CO_Data TestMaster_Data = CANOPEN_NODE_DATA_INITIALIZER(TestMaster);

