
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef PG2SLAVE_H
#define PG2SLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlave_Data;
extern UNS8 Input1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 Output1;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 Bumper1;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS32 Bumper2;		/* Mapped at index 0x2004, subindex 0x00*/
extern INTEGER32 YEncoder;		/* Mapped at index 0x2006, subindex 0x00*/

#endif // PG2SLAVE_H
